name: Build and Release

# Trigger the workflow when you push a tag starting with 'v'
on:
  push:
    tags:
      - 'v*'
  # Also allow manual trigger
  workflow_dispatch:

jobs:
  build:
    name: Build Windows Executable
    runs-on: windows-latest
    
    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Setup Rust toolchain
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc
    
    # Cache Cargo dependencies for faster builds
    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    # Build the project in release mode
    - name: Build release
      run: cargo build --release --target x86_64-pc-windows-msvc
    
    # Run tests to ensure everything works
    - name: Run tests
      run: cargo test --release
    
    # Move executable to root for easier access
    - name: Move executable
      run: |
        move target\x86_64-pc-windows-msvc\release\windows-system-cleaner.exe windows-system-cleaner.exe
    
    # Upload the executable as build artifact
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-system-cleaner
        path: windows-system-cleaner.exe
        retention-days: 90
    
    # Create GitHub release with the executable
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: windows-system-cleaner.exe
        generate_release_notes: true
        draft: false
        prerelease: false
        name: Release ${{ github.ref_name }}
        body: |
          ## Windows System Cleaner ${{ github.ref_name }}
          
          ### 🚀 What's New
          - Safe cleanup of temporary files and browser caches
          - Supports Chrome, Edge, Firefox, Brave, and Opera
          - Windows temp directories cleanup
          - Prefetch and thumbnail cache cleanup
          
          ### 📥 Download
          Download `windows-system-cleaner.exe` below and run as Administrator for best results.
          
          ### ⚠️ Requirements
          - Windows 10/11
          - Run as Administrator (recommended)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}